AWSTemplateFormatVersion: "2010-09-09"
Description: S3 bucket and DynamoDB table to use to manage the root terraform state

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  BucketName:
    Description: Name of S3 bucket
    Value: !Ref Bucket
  TableName:
    Description: Name of DynamoDB table
    Value: !Ref Table
